[tools]
bun = "latest"
go = "latest"
node = "latest"
npm = "latest"
"npm:@antfu/ni" = "latest"
"npm:@antfu/nip" = "latest"
"npm:@dotenvx/dotenvx" = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:@g2d/cli" = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@googleworkspace/cli" = "latest"
"npm:@microsoft/inshellisense" = "latest"
"npm:@openai/codex" = "latest"
"npm:@statsig/siggy" = "latest"
"npm:@tobilu/qmd" = "latest"
"npm:@typescript/analyze-trace" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:agent-browser" = "latest"
"npm:commitizen" = "latest"
"npm:corepack" = "latest"
"npm:firebase-tools" = "latest"
"npm:http-server" = "latest"
"npm:ngrok" = "latest"
"npm:portless" = "latest"
"npm:pyright" = "latest"
"npm:qnm" = "latest"
"npm:serve" = "latest"
"npm:skills" = "latest"
"npm:taze" = "latest"
"npm:tunnelmole" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vercel" = "latest"
"npm:wrangler" = "latest"
python = "latest"

[settings]
idiomatic_version_file = true
idiomatic_version_file_enable_tools = ["node", "go"]
status.missing_tools = "always"

[env]
MISE_PYTHON_PRECOMPILED_FLAVOR = "install_only_stripped"
